# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsExample
  pod 'SnapKit'
  pod 'RAMAnimatedTabBarController'
end
